version: '3.8'
services:
    webserver:
        build:
            context: ./phpApacheImage
        container_name: webserver
        restart: 'always'
        volumes:
            - ./sourceCode:/var/www/html/
        ports:
            - 8000:80
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: dbserver
        environment:
            - MYSQL_ROOT_PASSWORD=111222
        ports:
            - 3306:3306
        
    phpmyadmin:
        image: phpmyadmin
        ports:
            - 8001:80
        restart: always
        environment:
          - PMA_ARBITRARY=1
